### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ws_connect'

### ISSUE THREAD

**Issue by simplextech** [bachya/aioambient#21]
[https://github.com/miguelgrinberg/python-engineio/issues/152](https://github.com/miguelgrinberg/python-engineio/issues/152)

I just started getting the error in the title.  I'm fairly sure it's related to the upstream engineio issue but I wanted to validate.

Full error:

> 2019-12-11 01:06:19,073 [NodeServer] [ERROR] Task exception was never retrieved
future: <Task finished coro=<Controller.AmbientWeather() done, defined at ./ambientweather-poly.py:239> exception=AttributeError("'NoneType' object has no attribute 'ws_connect'")>
Traceback (most recent call last):
  File "./ambientweather-poly.py", line 604, in AmbientWeather
    await client.websocket.connect()
  File "/usr/local/lib/python3.7/site-packages/aioambient/websocket.py", line 76, in connect
    transports=["websocket"],
  File "/usr/local/lib/python3.7/site-packages/socketio/asyncio_client.py", line 108, in connect
    engineio_path=socketio_path)
  File "/usr/local/lib/python3.7/site-packages/engineio/asyncio_client.py", line 76, in connect
    url, headers, engineio_path)
  File "/usr/local/lib/python3.7/site-packages/engineio/asyncio_client.py", line 251, in _connect_websocket
    ws = await self.http.ws_connect(
AttributeError: 'NoneType' object has no attribute 'ws_connect'

**Comment by bachya** [comment]
This isn't an issue with `aioambient`; as you've deduced, [it's an issue with `python-engineio`](https://github.com/miguelgrinberg/python-engineio/issues/152).

**Comment by bachya** [comment]
That said, I’m going to need to pin the latest `python-engineio` version once the bug is fixed, so I’ll keep this issue open until that can be done.
