### ISSUE TITLE
Issues with continusous run and reconnecting on disconnect

### ISSUE THREAD

**Issue by kyrlon** [bachya/aioambient#523]
I see that there was an [issue](https://github.com/bachya/aioambient/issues/7) mentioned about reconnecting, but after a prolonged time, I get a disconnect and have to restart everything to have a stable connection. Below is the error message I get:
```
INFO:aioambient:Received packet PING data
INFO:aioambient:Received packet PING data
INFO:aioambient:Sending packet PONG data
INFO:aioambient:Received packet PING data
INFO:aioambient:Sending packet PONG data
INFO:aioambient:Watchdog expired – calling reconnect
INFO:aioambient:Sending packet MESSAGE data 1
INFO:aioambient:Sending packet CLOSE data None
INFO:aioambient:Engine.IO connection dropped
INFO:asyncio:Client has disconnected from the websocket
INFO:aioambient:Write loop: WebSocket connection was closed, aborting
INFO:aioambient:Exiting write loop task
WARNING:aioambient:Server sent close packet data None, aborting
INFO:aioambient:Waiting for write loop task to end                                                                                                          INFO:aioambient:Exiting read loop task                                                                                                                      INFO:aioambient:Attempting WebSocket connection to wss://rt2.ambientweather.net/socket.io/?api=1&applicationKey=[KEY_HERE]&transport=websocket&EIO=4                                                                                                              
INFO:aioambient:WebSocket connection accepted with {'sid': 'zR2WAc9J_NXoQK3EZcs6', 'upgrades': [], 'pingInterval': 25000, 'pingTimeout': 20000}             INFO:aioambient:Engine.IO connection established                                                                                                            INFO:aioambient:Sending packet MESSAGE data 0{}                                                                                                             INFO:aioambient:Received packet MESSAGE data 4{"message":"applicationKey-invalid"}                                                                          INFO:aioambient:Connection to namespace / was rejected                                                                                                      INFO:aioambient:Sending packet CLOSE data None                                                                                                              INFO:aioambient:Engine.IO connection dropped                                                                                                                INFO:aioambient:Write loop: WebSocket connection was closed, aborting                                                                                       INFO:aioambient:Exiting write loop task                                                                                                                     WARNING:aioambient:Server sent close packet data None, aborting                                                                                             INFO:aioambient:Waiting for write loop task to end
INFO:aioambient:Exiting read loop task                                                                                                                      ERROR:asyncio:Task exception was never retrieved                                                                                                            future: <Task finished name='Task-9302' coro=<WebsocketWatchdog.on_expire() done, defined at /home/kyrlon/.venv/lib/python3.8/site-packages/aioambient/websocket.py:41> exception=WebsocketError(ConnectionError('One or more namespaces failed to connect'))>
Traceback (most recent call last):
  File "/home/kyrlon/.venv/lib/python3.8/site-packages/aioambient/websocket.py", line 156, in connect
    await self._sio.connect(
  File "/home/kyrlon/.venv/lib/python3.8/site-packages/socketio/async_client.py", line 175, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kyrlon/.venv/lib/python3.8/site-packages/aioambient/websocket.py", line 44, in on_expire
    await self._action()
  File "/home/kyrlon/.venv/lib/python3.8/site-packages/aioambient/websocket.py", line 177, in reconnect
    await self.connect()
  File "/home/kyrlon/.venv/lib/python3.8/site-packages/aioambient/websocket.py", line 166, in connect
    raise WebsocketError(err) from err
aioambient.errors.WebsocketError: One or more namespaces failed to connect
```

Any suggestions on this issue are welcomed!

**Comment by bachya** [comment]
What version of the library are you using?

**Comment by kyrlon** [comment]
Python3 version: 3.8.10

aioambient==2021.12.0

**Comment by bachya** [comment]
That's quite an old version; try upgrading to the latest (2024.01.0) and see if that resolves your issue. Note that you'll likely need to upgrade your Python version: we support the most recent three versions, so you'll need to go to a minimum of 3.10.

**Comment by kyrlon** [comment]
Wow. I think that is definitely the problem and a complete oversight on my end. I'll update my python3 to the supported version to have the right module.

**Comment by kyrlon** [comment]
After about  29 hours, 45 minutes, and 29 seconds. , I still receive a similar error
```
2024-07-03 08:40:47,375 [MainThread  ] [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-11008' coro=<WebsocketWatchdog.on_expire() done, defined at /home/kyrlon/.venv/lib/python3.11/site-packages/aioambient/websocket.py:50> exception=WebsocketError(ConnectionError('One or more namespaces failed to connect'))>
Traceback (most recent call last):
  File "/home/kyrlon/.venv/lib/python3.11/site-packages/aioambient/websocket.py", line 226, in connect
    await self._sio.connect(
  File "/home/kyrlon/.venv/lib/python3.11/site-packages/socketio/async_client.py", line 175, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kyrlon/.venv/lib/python3.11/site-packages/aioambient/websocket.py", line 53, in on_expire
    await self._action()
  File "/home/kyrlon/.venv/lib/python3.11/site-packages/aioambient/websocket.py", line 245, in reconnect
    await self.connect()
  File "/home/kyrlon/.venv/lib/python3.11/site-packages/aioambient/websocket.py", line 234, in connect
    raise WebsocketError(err) from err
aioambient.errors.WebsocketError: One or more namespaces failed to connect
```
